### ISSUE TITLE
No checksums? Nor at least SSL downloads. WTF is this?

### ISSUE THREAD

**Issue by nextgenthemes** [shadowproject/shadow#18]
http://www.aboutshadow.com/index.php/resources/downloads

Seriously? So people should blindly download your stuff and trust what comes down the http pipe?

You claim to care about privacy, that great! because my problem with Bitcoin and Altcoins was always the privacy thing.

In my opinion it greatly damages your reputation if you only provide downloads in this total insecure manner. How you think people should trust you if you start like this?

**Comment by LiteBit** [comment]
sha256sums can be found here: https://github.com/ShadowProject/shadow/releases
