### ISSUE TITLE
Staking to a different address

### ISSUE THREAD

**Issue by allienworks** [shadowproject/shadow#39]
I'd love to see an option to send stake rewards to a different address (e.g. charity, developers etc.)

I offer [bounty on Bountysource](https://www.bountysource.com/issues/37577948-staking-to-a-different-address) to anyone willing to make this a reality.

**Comment by LiteBit** [comment]
Love this idea. I sketched up an idea for a page or tab for this. http://imgur.com/er58zaR

You could hardcore and identify a few key addresses and other spots are user filled. Then one could check address or a addresses to stake too and assign a percent totalling 100% or less.

Stake reward would be divided as specified and remainder to user owned address like normal.

**Comment by allienworks** [comment]
Interesting approach @LiteBit! I like it, however I'd add option to manually select address for rewards. I shamelessly took your idea with what I have in my head - this came out of it:
![](http://i.imgur.com/4EqH97e.png)
You could specify the number of addys that will get the %s of your rewards; by default with text field for addresses OR select from prepared "address templates" for charities/devs etc. This could be a subject of some community vote (so it's not redundantly crowded).

**Comment by kewde** [comment]
@allien @litebit :+1:

I'll put together the rough framework for HTML along with C++,
Any candidates for styling it with CSS?

**Comment by allienworks** [comment]
@kewde I'm up for CSS, for sure!

**Comment by kewde** [comment]
I'll put together a working barebone HTML that is linked to the backend and then let you loose on it :smile:

**Comment by kewde** [comment]
This issue has a bounty!
![https://api.bountysource.com/badge/issue?issue_id=37577948](https://api.bountysource.com/badge/issue?issue_id=37577948)
