### ISSUE TITLE
SDC umbra 1.5.0

### ISSUE THREAD

**Issue by PabloEscobarZ** [shadowproject/shadow#40]
what's the path for the blockchain?
shadowcash umbra platform.

**Comment by rynomster** [comment]
on which OS? it hasn't changed, we figured best to leave it where it is for now.
`%appdata%/shadowcoin` on windows I believe, `~/.shadowcoin` on linux and `~/Library/Application\ Support/ShadowCoin` on OSX

**Comment by rynomster** [comment]
https://slack.shadowproject.io || https://shadowproject.slack.com

**Comment by timthomascode** [comment]
On OSX it's ~/Users/<yourusername>/Library/Application Support/Shadowcoin/
