### ISSUE TITLE
Need to see url link destination in chat

### ISSUE THREAD

**Issue by LiteBit** [shadowproject/shadow#41]
When I hover over the link text in chat I don't get any indication where it's going. It should give pop-up window showing destination address.

![capture](https://cloud.githubusercontent.com/assets/6236019/18287960/5496acce-7447-11e6-8b40-af882feb9f0f.JPG)

The red "test" text is a link, but I don't know where it goes.

**Comment by kewde** [comment]
I believe we should get rid of it.

**Comment by rynomster** [comment]
I think it's nice to have links in chats, it makes life easier. We could add a tool tip to it, or we could just get rid of those types of links and highlight normal URLs.. Either way, if you copy the message you'll be able to see the contents of the links.

**Comment by LiteBit** [comment]
I like having them, they can be helpful in conversation. Tool tip would be good or an option to not rename link.

**Comment by rynomster** [comment]
https://www.bountysource.com/issues/37630996-need-to-see-url-link-destination-in-chat

**Comment by kewde** [comment]
I'll do this, it's easy.

**Comment by LiteBit** [comment]
If IP addresses are leaking because of links or images I'd just not add them.

**Comment by kewde** [comment]
Fix was merged to GUI.
Should be fixed in next release :+1:

**Comment by rynomster** [comment]
fixed in 1.5.0.1
