### ISSUE TITLE
Correct SDT nomenclature needs to appear for Private coin send / balance transfer

### ISSUE THREAD

**Issue by LiteBit** [shadowproject/shadow#43]
When in Send window the currency code SDC appears in Balance box for both public and private selections. This happens for both "Make Payment" and "Balance Transfer" tabs. Screenshots below:

![capture](https://cloud.githubusercontent.com/assets/6236019/18334281/555417e8-7544-11e6-92c1-ec15b3f795ad.PNG)
![capture2](https://cloud.githubusercontent.com/assets/6236019/18334284/5998074c-7544-11e6-877a-a35106ec06b3.PNG)

https://doc.shadowproject.io/#shadowtokens-sdt labels the "private" coins as SDT or ShadowTokens.

**Comment by dasource** [comment]
Interesting SDT came about to distinguish the two ... but in reality they are still SDC ...
I guess there is no harm in replacing SDC on Private Balance to "Shadow" and being done with SDT in full?

What do others think?

**Comment by kewde** [comment]
Will fix tomorrow along with deleting GUI text inputs when switching between "make payment" <-> "balance transfer".

**Comment by LiteBit** [comment]
I've always like "Shadow" over SDT. Interesting to know that it's really all just SDC. Our docs could be clearer with that maybe.

**Comment by dasource** [comment]
@LiteBit Shadow is the correct terminology per whitepaper. Lets stick to that
@code, thanks.

**Comment by kewde** [comment]
I think for now we'll just stick with SDC. 
Keeping it simple, one word to define the currency. 
Reving the concept of Shadow/SDT is a hassle, we moved to public vs private balance for a reason.
