### ISSUE TITLE
RPC issues on version 1.5

### ISSUE THREAD

**Issue by otrsconfig** [shadowproject/shadow#49]
RPC works great on 1.4, but on 1.5 I can't connect to either the default port nor to the port I set up using the shadow.conf file, using rpcport=PortNumber

Happens on the Windows 64 version, on 2 different Windows 7 OS.

**Comment by kewde** [comment]
Hi,

Please post your whole configuration file (shadowcoin.conf), minus the password and user.

**Comment by otrsconfig** [comment]
Hi, this seems to be working now. It's weird, it wasn't at some point.
But now it is, with this config, on 1.5.

server=1
rpcuser=USER
rpcpassword=PASSWORD
maxconnections=4
