### ISSUE TITLE
Unable to change the data directory for version 1.4

### ISSUE THREAD

**Issue by otrsconfig** [shadowproject/shadow#50]
On version 1.4 (haven't tried on 1.5 since I have another issue with that one), it apparently ignores the -datadir=Directory switch when calling the executable.

Am I doing something wrong? How can I set up another directory?
I'm doing this:
D:\Shadow\umbra.exe -datadir=D:\Shadow

**Comment by kewde** [comment]
Hi @otrsconfig,
What version of Windows are you running?

One of our team members has tested this and it's working for them.
I'll be trying this out myself to verify.

@rynomster any idea?

**Comment by kewde** [comment]
You may want to try shifting to the following configuration; Might be an issue with having exe in the datadir.

D:\Shadow\umbra.exe -datadir=D:\Shadow\datadir

**Comment by kewde** [comment]
I'm having the same issue, datadir is being ignored.
We'll look into this, thank you.

**Comment by otrsconfig** [comment]
Hi, thanks for looking into it.
1.4, tried on the same and different partitions, with and without a trailing "\", same behavior.

**Comment by dasource** [comment]
@otrsconfig I am pretty sure the syntax on the QT Wallet is `umbra.exe -conf -datadir=D:\Shadow\datadir`

**Comment by otrsconfig** [comment]
Hi, just tried with this and it's still using the datadir at %APPDATA%\Shadow when running like this:

`C:\shadow_1.4.0.3_win64\shadow.exe -conf -datadir=E:\Shadow\data`

Happens with 1.4 and 1.5. If I use a directory that does not exist, I get a warning and the software won't launch.
But it keeps using the BC at %APPDATA%.

Thanks.

**Comment by kewde** [comment]
Verified and looking into :+1:

**Comment by kewde** [comment]
@rynomster could you peak into this if you happen to have a bit of time?

**Comment by rynomster** [comment]
Will have a look today

**Comment by rynomster** [comment]
it seems setting -datadir is not affective.
What does work is creating a conf file in E:\Shadow\data, i.e.: `E:/shadow/data/umbra.conf`, and running the exe with `umbra.exe -conf=E:/shadow/data/umbra.conf
Inside the config file I added `datadir=E:/shadow/data` on a new line and it seems to work.

I'll the datadir arg, its not being set in init.cpp

**Comment by kewde** [comment]
Thanks @rynomster

**Comment by kewde** [comment]
@otrsconfig this is fixed in #63 
We can close this issue now.
