### ISSUE TITLE
Allow unlock for Chat option

### ISSUE THREAD

**Issue by rynomster** [shadowproject/shadow#51]
Currently we only have Unlock for staking, or full unlock. We need to add an option for unlock for secure messaging too. The private keys are required in order to decrypt messages, so an encrypted wallet needs to be unlocked in order to send and receive messages.

Files and functions affected:
https://github.com/shadowproject/shadow/blob/v1.5.0.1/src/rpcwallet.cpp#L1590
https://github.com/shadowproject/shadow/blob/v1.5.0.1/src/wallet.h#L26
https://github.com/shadowproject/shadow/blob/v1.5.0.1/src/wallet.cpp#L184
https://github.com/shadowproject/shadow/blob/v1.5.0.1/src/walletdb.cpp#L15
https://github.com/shadowproject/shadow/blob/v1.5.0.1/src/qt/askpassphrasedialog.cpp
https://github.com/shadowproject/shadow/blob/v1.5.0.1/src/qt/forms/askpassphrasedialog.ui
https://github.com/shadowproject/shadow/blob/v1.5.0.1/src/qt/shadowbridge.cpp
https://github.com/shadowproject/shadow/blob/v1.5.0.1/src/qt/shadowgui.cpp
https://github.com/shadowproject/shadow/blob/v1.5.0.1/src/qt/walletmodel.cpp

**Comment by kewde** [comment]
Agreed.

**Comment by kewde** [comment]
@rynomster you can assign me to this issue.
I've fixed this tonight, will be pushing tomorrow.

**Comment by rynomster** [comment]
fixed in #62
