### ISSUE TITLE
There is no install target in the qmake project

### ISSUE THREAD

**Issue by elopio** [shadowproject/shadow#58]
qmake has a simple way to define the files that have to be installed when make install is called:
https://doc.qt.io/qt-5/qmake-advanced-usage.html#installing-files

This project just leaves the binary in the build path. I think it should offer also the way to install it in a system wide path.

**Comment by rynomster** [comment]
We can add it, possibly in /usr/local/bin by default?

**Comment by elopio** [comment]
I think so. I'll prepare the PR for you to review.

**Comment by rynomster** [comment]
Awesome thank you :)
