### ISSUE TITLE
Balance transfer bug

### ISSUE THREAD

**Issue by sh4d0v1** [shadowproject/shadow#64]
I am on umbra version v1.5.0.2-21-g27ce3db (latest git).

I want to send some coins from a stealth address to my default non-stealth address. When I click `balance transfer` and `from account: private` (without `advanced options`) umbra is effectively trying to send the coins from my stealth address to my (the same) stealth address.
If I take the advanced options and do `from account: private` and `to account: public` there is still my stealth address chosen as `pay to`. If I change this to my default address (I choose from the address book) and send the coins, after taking the password I get a pop-up error `Invalid stealth address`.

In effect I can't move coins from stealth to non-stealth with this bug.
![shadow-bug](https://cloud.githubusercontent.com/assets/21977506/20223209/c6a3674c-a838-11e6-9496-1468444d12d2.png)
![shadow-bug2](https://cloud.githubusercontent.com/assets/21977506/20223210/c8edd38e-a838-11e6-8a3d-c120a3f58a1f.png)

**Comment by kewde** [comment]
This issue can be closed.

You can only send SDT to stealth addresses.
You can send SDC to both normal and stealth addresses.

The main reason is to prevent people from sending SDT->SDC directly from the normal address it came from.
