### ISSUE TITLE
Default address vs public key

### ISSUE THREAD

**Issue by msmee94** [shadowproject/shadow#88]
Hi, I sent my SDC to the 'default address' on the receive tab in the wallet. But i never received the SDC in my wallet, is this because i should've used the public key, and is there any way I can recover the SDC? Feeling like an idiot haha.

**Comment by rynomster** [comment]
Is your wallet synced up? You are supposed to send it to your address

**Comment by kewde** [comment]
Please do not use Github issues for support.

https://riot.im/app/#/room/#shadowproject:matrix.org

**Comment by kewde** [comment]
Please do not use Github issues for support.

https://riot.im/app/#/room/#shadowproject:matrix.org
