### ISSUE TITLE
mblk instead of block

### ISSUE THREAD

**Issue by mmitech** [shadowproject/shadow#89]
I am trying to parse the block data, I've already figured out that the P2P message for a new block is 'mblk' instead of 'block' (like in Bitcoin and most alts), what I can't figure out is how to parse that message!

In other words, I am trying to make a fork of bitcore that would work with shadow to use it bitpay repos (Insight, Copay...). and the issue relies here on:

https://github.com/bitpay/bitcore/blob/v0.1.34/lib/Connection.js#L470-L485
https://github.com/bitpay/bitcore/blob/v0.1.34/lib/Block.js#L19-L76

**Comment by rynomster** [comment]
Mblk is multiblock, it sends multiple blocks at a time for clients that are
a few blocks behind. I think it's easiest just to take the code out of
main.cpp, and recompile the daemon.

**Comment by mmitech** [comment]
yes removing the multiblock code seems to fix the issue, but I am having problems with the tx message as well! the message I get for tx has completely different hash than the one is confirmed or the one in the mempool ! is data parsed differently here as well?

**Comment by rynomster** [comment]
Shadow used to use scrypt, have a look at our bitcore / insight forks to
add the scrypt support

**Comment by mmitech** [comment]
OK I see where I went wrong, you said "used to use scrypt", I am on master now and I still see that you use scrypt for blocks and transactions.

BTW, am I safe to use the repos you have published already?

**Comment by rynomster** [comment]
They're very outdated, but you should be able to get a block explorer up
and a few of the older insight apis still work
